# Generated by Django 4.1.3 on 2022-11-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("retail_price", models.IntegerField(default=0)),
                ("discounted_price", models.ImageField(default=0, upload_to="")),
                ("brand", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000)),
                ("image_url", models.URLField()),
            ],
        ),
    ]
